# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sanfy Edu
email: me@sanfy.in
description: > # this means to ignore newlines until "baseurl:"
  Sanfy Education Portal.
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edu.sanfy.in/" # the base hostname & protocol for your site

#sidebar
default-image: default.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Sanfy.In
copyright:
   name: Sanfy.In
   link: 'http://www.sanfy.in'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

kramdown:
  parse_block_html: true

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: blog-sanfy-in

#social
facebook: http://facebook.com/sanfyin
quora: http://quora.com/#
twitter: http://twitter.com/#
github: http://github.com/sanfyin

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/sanfyin/
fb-page-title: Sanfy.In

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

# Ignore node_modules
exclude: ['node_modules']

